USE [master]
GO

/****** Object:  Database [Examen]    Script Date: 02/03/2022 21:47:53 ******/
CREATE DATABASE [Examen]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Examen', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.RUIZ\MSSQL\DATA\Examen_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Examen_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.RUIZ\MSSQL\DATA\Examen_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Examen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Examen] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Examen] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Examen] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Examen] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Examen] SET ARITHABORT ON 
GO

ALTER DATABASE [Examen] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Examen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Examen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Examen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Examen] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Examen] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Examen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Examen] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Examen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Examen] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Examen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Examen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Examen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Examen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Examen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Examen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Examen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Examen] SET RECOVERY FULL 
GO

ALTER DATABASE [Examen] SET  MULTI_USER 
GO

ALTER DATABASE [Examen] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Examen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Examen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Examen] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Examen] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Examen] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Examen] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Examen] SET  READ_WRITE 
GO


